language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

addons:
  code_climate:
    repo_token: 4d7548ab7836ec0d46e360e26325d66831856751457539a46cf126a30ca086e5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer update --no-interaction --prefer-lowest

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter