language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit